language: ruby

cache: bundler

sudo: false

bundler_args: --without debug
script: "bundle exec rspec spec"

rvm:
  - 2.2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9
  - rbx-3

matrix:
  allow_failures:
    - rvm: jruby-9
    - rvm: rbx-3
      
dist: trusty